name: Vercel Production Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.PRODUCTION_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PRODUCTION_VERCEL_PROJECT_ID }}

jobs:
  Vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@43.3.0

      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=production --token=${{ secrets.PRODUCTION_VERCEL_TOKEN }}

      # - name: Build Project Artifacts
      #   run: vercel build --prod --token=${{ secrets.PRODUCTION_VERCEL_TOKEN }}

      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.PRODUCTION_VERCEL_TOKEN }}
